# Generated by Django 3.1.5 on 2021-02-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(help_text='영상 내용 설명', max_length=500, null=True, verbose_name='설명')),
                ('release_dt', models.DateField(null=True, verbose_name='개봉 일자')),
                ('running_time', models.IntegerField(verbose_name='재생시간')),
                ('director', models.CharField(max_length=100, verbose_name='제작자')),
                ('video_type', models.CharField(choices=[('movie', 'Movie'), ('drama', 'Drama')], max_length=50, verbose_name='영화/드라마 구분')),
                ('recommend', models.PositiveIntegerField(default=0, verbose_name='추천수')),
                ('grade', models.CharField(choices=[('all', '전체이용가'), ('12', '12세 이용가'), ('15', '15세 이용가'), ('19', '19세 이용가')], max_length=50, verbose_name='영상등급')),
            ],
        ),
    ]
