# Generated by Django 3.1.5 on 2021-02-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_link',
            field=models.URLField(max_length=350, verbose_name='VIDEO_URL'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_thumb',
            field=models.URLField(max_length=350, verbose_name='THUMBNAIL_URL'),
        ),
    ]
