# Generated by Django 3.1.5 on 2021-02-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20210204_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_link',
            field=models.URLField(default=1, max_length=350, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
