# Generated by Django 3.1.5 on 2021-02-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_video_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='vthumbnail',
            field=models.ImageField(null=True, upload_to='video/images', verbose_name='IMAGE'),
        ),
    ]
