# Generated by Django 3.1.5 on 2021-02-01 22:07

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('re_id', models.AutoField(primary_key=True, serialize=False, verbose_name='리뷰등록번호')),
                ('re_title', models.CharField(max_length=120, verbose_name='리뷰 제목')),
                ('content', tinymce.models.HTMLField(verbose_name='CONTENT')),
                ('create_dt', models.DateField(auto_now_add=True, verbose_name='작성일자')),
                ('modify_dt', models.DateField(auto_now=True, verbose_name='수정일자')),
                ('like', models.PositiveIntegerField(default=0, verbose_name='좋아요')),
            ],
        ),
    ]
