# Generated by Django 3.1.5 on 2021-02-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_review_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='read_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
