# Generated by Django 3.1.5 on 2021-02-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MTF_User',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='PWD')),
                ('age', models.PositiveIntegerField(verbose_name='나이')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('not-specified', 'Not Specified')], max_length=50, verbose_name='성별')),
                ('phone_number', models.CharField(max_length=120, verbose_name='연락처')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('name', models.CharField(max_length=150, verbose_name='이름')),
                ('joined_dt', models.DateTimeField(auto_now_add=True, verbose_name='가입일자')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='최근 로그인 일자')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('is_admin', models.BooleanField(default=False, verbose_name='관리자 여부')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
