# Generated by Django 3.1.5 on 2021-02-08 10:00

import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=128, unique=True, verbose_name='이메일')),
                ('password', models.CharField(max_length=128, verbose_name='PWD')),
                ('age', models.PositiveIntegerField(verbose_name='나이')),
                ('gender', models.CharField(choices=[('male', '남성'), ('female', '여성')], max_length=10, verbose_name='성별')),
                ('phone', models.CharField(max_length=13, verbose_name='전화번호')),
                ('name', models.CharField(max_length=30, verbose_name='이름')),
                ('joined_dt', models.DateField(auto_now_add=True, verbose_name='가입일자')),
                ('last_login', models.DateField(auto_now=True, verbose_name='최근 로그인 일자')),
                ('is_active', models.BooleanField(default=True, verbose_name='ID 활성화 여부')),
                ('is_admin', models.BooleanField(default=False, verbose_name='관리자 여부')),
                ('is_staff', models.BooleanField(default=False, verbose_name='직원 여부')),
                ('bookmark', models.CharField(blank=True, max_length=50, null=True, verbose_name='찜한 영상')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
