# Generated by Django 3.1.5 on 2021-02-08 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210208_1011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '유저', 'verbose_name_plural': '유저들'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
