# Generated by Django 3.1.5 on 2021-02-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_user_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bookmark',
            field=models.CharField(max_length=50, null=True, verbose_name='찜한 영상'),
        ),
    ]
