# Generated by Django 3.1.5 on 2021-02-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bookmark',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='찜한 영상'),
        ),
    ]
