# Generated by Django 3.1.5 on 2021-02-06 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210206_1210'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
